### ISSUE TITLE
Faraday client url params does not match #params_to_query

### ISSUE THREAD

**Issue by kylesnowschwartz** [MagicTheGathering/mtg-sdk-ruby#2]
Hi there!

After running the following command `MTG::Card.where(name: "Elspeth, Sun's Champion").all.map(&:name).uniq` expecting to get back `["Elspeth, Sun's Champion"]`, I was surprised to see the following result `["Elspeth, Knight-Errant", "Elspeth Tirel", "Elspeth, Sun's Champion"]`.

I dug into the code to see how the QueryBuilder and RestClient worked. The #params_to_query method looks fine, but I saw that after running 
`response = MTG::RestClient.get(MTG::Card.Resource, {name: "Elspeth, Sun's Champion"} )` `response.env.url => #<URI::HTTPS https://api.magicthegathering.io/v1/cards?name=Elspeth%2C+Sun%27s+Champion>`
when I thought it would return 
`#<URI::HTTPS https://api.magicthegathering.io/v1/cards?name=%22Elspeth,%20Sun%27s%20Champion%22>`

Kind of stuck as to where to go from here, is this expected behavior?

**Comment by adback03** [comment]
Be default, the **name** URL parameter will take in a comma separated list of names. In order to do an exact match, you have to surround it in quotes. So your Ruby code would look like this (notice the escaped quotes):

```
MTG::Card.where(name: "\"Elspeth, Sun's Champion\"").all.map(&:name).uniq
```

Your original example is actually saying to retrieve cards with names like "Elspeth" or "Sun's Champion".

Perhaps I should add on some optional bool parameter on whether or not to perform an exact match to make it more clear? Until then, I hope that solves your issue!

**Comment by kylesnowschwartz** [comment]
Ah yes, I see, thanks and sorry about that!

**Comment by adback03** [comment]
No problem! Let me know if you have any other issues.
